global:
  scrape_interval: 15s

scrape_configs:
  - job_name: 'jupyterhub'
    metrics_path: '/hub/metrics'
    static_configs:
      - targets: ['jupyterhub:8000']

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['cadvisor:8080']
